name: "nix-build"
on:
  pull_request_target:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v13
    - uses: DeterminateSystems/magic-nix-cache-action@v7
    - name: Build some-pkgs
      run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake ".#packages"
  nix-flake-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v13
    - uses: DeterminateSystems/magic-nix-cache-action@v7
    - name: Build the checks
      run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake ".#checks.$(nix eval --raw --impure --expr builtins.currentSystem)"
